server:
  port: 8102

dubbo:
  application:
    name: taotao_search_service
  registry:
    address: zookeeper://192.168.8.250:2181
  scan:
    base-packages: com.study.demo.taotao_search_service.impl
  provider:
    timeout: 6000
  protocol:
    port: 20889

spring:
  activemq:
    broker-url: tcp://192.168.25.129:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 10